### ISSUE TITLE
PyDrive not working with oauth2client version 4.0

### ISSUE THREAD

**Issue by dwai1714** [googledrive/PyDrive#78] opened 2016-10-16 19:28 UTC
oauth2client.file.CredentialsFileSymbolicLinkError not found error

**Comment by RNabel** [comment] 2016-10-17 15:10
Thank you for posting this here :) 

Could you please post instructions on how to reproduce the error, and a traceback?

**Comment by purbayasetiya** [comment] 2016-10-18 08:35
Hey, i also have the same problem. At the beginning i try to run the code on windows, and it worked. But when i try to run the code on my raspberry pi (OS raspbian) the code show me error about symboliclink.

i run this code 
`from pydrive.auth import GoogleAuth

gauth = GoogleAuth()
gauth.LocalWebserverAuth()`

import error : oauth2client.file.CredentialsFileSymbolicLinkError not found error
the error is from auth.py line 15 which is "from oauth2client.file import CredentialsFileSymbolicLinkError"

i follow the same instruction on authentication page [auth page] (http://pythonhosted.org/PyDrive/quickstart.html#authentication) when i try on windows and raspbian.

**Comment by RNabel** [comment] 2016-10-18 09:28
@purbayasetiya Thank you for the details!

The problem is that PyDrive relies on *google-api-python-client* which in turn relies on *oauth2client*. 
Now *PyDrive* gets its version of oauth2client from the *google-api-python-client*, but is not compatible with 4.0.0 (which you can tell by the semantic versioning is not necessarily backwards compatible with 3.x.x).

So, basically, PyDrive needs to compatible with *oauth2client* 4.0.0. If either of you, @purbayasetiya and @dwai1714, need this urgently, replace lines 307-311 in auth.py with:

```python
try:
      storage = Storage(credentials_file)
      self.credentials = storage.locked_get()
  except IOError:
      raise InvalidCredentialsError('Credentials file cannot be symbolic link')
```

and remove line 15:
```python
from oauth2client.file import CredentialsFileSymbolicLinkError
```

**Comment by dwai1714** [comment] 2016-10-18 17:54
Hi Robin 
Thank you very much. For the time being I made it backward compatible. Once you update the package I will update my project.On a separate note if we move to google API version 3, do we need changes. If thats the case I will be happy to contribute.Apologies, you made PyDrive so simple that I did not peek inside too much :)
ThanksDC

**Comment by keliomer** [comment] 2016-10-18 20:57
Related - Getting below when trying to run anything out of pydrive.auth

` File "C:\Python27\lib\site-packages\pydrive\auth.py", line 17, in <module>
    from oauth2client.util import scopes_to_string
ImportError: No module named util`


Basesd on discussion on the [pydrive issues forum](https://github.com/google/oauth2client/pull/579) util has been merged into the "private" _helpers module.

**Comment by keliomer** [comment] 2016-10-21 21:42
Status update? I know the IOError replacement is only a stop-gap. What needs to be checked for oauth2client 4.0.0 compatibility from a testing standpoint?

**Comment by fauzanzaid** [comment] 2016-10-22 05:08
The current pydrive seems to be compatible with this [older google api python client package](https://github.com/gsutil-mirrors/google-api-python-client/tree/master/oauth2client).

**Comment by RNabel** [comment] 2016-10-23 18:32
Quick update: The plan is to add the oauth dependency explicitly to setup.py, fix incompatibilities until all tests pass. I will not be able to do this in the next days. 

If any of you have time to fix these errors (which would be amazing), I will review PRs asap (<24hrs).

**Comment by keliomer** [comment] 2016-10-24 16:14
[PR here](https://github.com/googledrive/PyDrive/pull/79)

**Comment by RNabel** [comment] 2016-10-24 20:08
@keliomer thank you so much for the PR. I have reviewed and merged it (althouh GitHub doesn't seem to recognize it :( ). I'll leave this issue open until the new version is pushed to PyPI.

**Comment by RNabel** [comment] 2016-10-24 20:56
Alright, the new version is live on [PyPI](https://pypi.python.org/pypi/PyDrive) - crises averted. Thank you again for all of your input!

**Closed** 2016-10-24 20:56 UTC
Labels: bug

**Comment by dwai1714** [comment] 2016-11-20 18:08
This works great now. 
Thanks a lot.

**Comment by hamza-carameltech** [comment] 2017-10-06 07:31
File "/opt/python/run/venv/lib/python2.7/site-packages/pydrive/auth.py", line 224, in LocalWebserverAuth
[Fri Oct 06 06:56:53.809651 2017] [:error] [pid 21696]     raise AuthenticationError()
[Fri Oct 06 06:56:53.809653 2017] [:error] [pid 21696] AuthenticationError
[Fri Oct 06 06:57:11.600320 2017] [:error] [pid 21696] Failed to start a local web server. Please check your firewall
[Fri Oct 06 06:57:11.600350 2017] [:error] [pid 21696] settings and locally running programs that may be blocking or
[Fri Oct 06 06:57:11.600355 2017] [:error] [pid 21696] using configured ports. Default ports are 8080 and 8090.
anyone know how to resolve this issue?
